! 7-JI_Rast-Maqam_Eight-Echos.scl
! 7-tone Just Intonation 11-Limit mode combining two disjunct Rast tetrachords according to Mansour Zalzal’s lute tuning as described by al-Farabi, where the ratios including prime number 11 are alterations of 3-Limit versions, coinciding with the Eight Echos or Fourth Plagal of Byzantine Psaltic Chant.
!
7-JI Rast Maqam - Eight Echos
7
!
9/8
27/22
4/3
3/2
27/16
81/44
2/1
